In [1]:
import os

In [2]:
import os.path

In [3]:
import time
import csv
import numpy
from datetime import datetime
import pandas as pd
import numpy as np

In [4]:
# Change to top level of extracted data archive
os.chdir("C:/Users/jhoff/Desktop/TableauHW/citidata")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/Users/jhoff/Desktop/TableauHW/citidata'

In [5]:
new = os.getcwd().replace("\\","/")

In [6]:
filepaths = []
for dirpath, dirnames, filenames in os.walk(new):
    for filename in [f for f in filenames if f.endswith(".csv")]:
        filepaths.append("." + os.path.join(dirpath, filename)[len(new):].replace("\\","/"))

In [7]:
rowcounter = 0
station = {}
name = {}
lat = {}
lng = {}

for filename in filepaths:
    with open(filename, newline="") as csvfile:
        csvreader = csv.reader(csvfile, delimiter=",")

        next(csvreader)                 # skips header row
        
        # Iterates through each row in csv
        for row in csvreader:
            
            rowcounter += 1

            # if candidate not in dict, adds key and initializes value
            if row[3] not in station:
                station[row[3]] = 0

            station[row[3]] += 1     # increments dictionary value
            
            if row[3] not in name:
                name[row[3]] = row[4]
                
            if row[3] not in lat:
                if row[5] != '0.0':
                    lat[row[3]] = float(row[5])
                
            if row[3] not in lng:
                if row[6] != '0.0':
                    lng[row[3]] = float(row[6])

In [8]:
df = pd.DataFrame([station, name, lat, lng]).T
df.columns = ['rides', 'start_station_name', 'start_station_lat', 'start_station_lng']

In [9]:
df

      rides       start_station_name start_station_lat start_station_lng
3183   6453           Exchange Place           40.7162          -74.0335
3184   2706              Paulus Hook           40.7141          -74.0336
3185   2613                City Hall           40.7177          -74.0438
3186  13107            Grove St PATH           40.7196          -74.0431
3187   3138                Warren St           40.7211          -74.0381
3191    384                 Union St           40.7182          -74.0836
3192   2412       Liberty Light Rail           40.7112          -74.0557
3193    933             Lincoln Park           40.7246          -74.0784
3194   1758          McGinley Square           40.7253          -74.0676
3195   5445                  Sip Ave           40.7307          -74.0638
3196    828           Riverview Park           40.7443           -74.044
3198    915         Heights Elevator           40.7487          -74.0404
3199   3369             Newport Pkwy           40.7287          -74.0321
3201    414                   Dey St           40.7377          -74.0669
3202   4689             Newport PATH           40.7272          -74.0338
3203   6705            Hamilton Park           40.7276          -74.0442
3205   1617        JC Medical Center           40.7165          -74.0496
3206   1098                  Hilltop           40.7312          -74.0576
3207   1755              Oakland Ave           40.7376          -74.0525
3209   2445             Brunswick St           40.7242          -74.0507
3210   1527           Pershing Field           40.7427          -74.0518
3211   3168               Newark Ave           40.7215          -74.0463
3212    909          Christ Hospital           40.7348          -74.0504
3213   2853           Van Vorst Park           40.7185          -74.0477
3214   2220         Essex Light Rail           40.7128          -74.0365
3220    813        5 Corners Library            40.735          -74.0595
3225   1296    Baldwin at Montgomery           40.7237          -74.0642
3267   3090             Morris Canal           40.7124          -74.0385
3268    783           Lafayette Park           40.7135          -74.0629
3269   2391          Brunswick & 6th            40.726          -74.0504
3270   2457          Jersey & 6th St           40.7253          -74.0456
3272   2436             Jersey & 3rd           40.7233           -74.046
3273   2175             Manila & 1st           40.7217          -74.0429
3275   2076           Columbus Drive           40.7184          -74.0389
3276   3972         Marin Light Rail           40.7146          -74.0428
3277    399  Communipaw & Berry Lane           40.7144          -74.0666
3278   1659         Monmouth and 6th           40.7257          -74.0488
3279   1791              Dixon Mills           40.7216            -74.05
3280    921              Astor Place           40.7193          -74.0713
3281    771      Leonard Gordon Park           40.7459          -74.0573
3426      6               JCBS Depot           40.7097          -74.0686
3481   1221                  York St           40.7165           -74.041
3483   1212            Montgomery St           40.7194           -74.051
3638   2901            Washington St           40.7243          -74.0355
3639   4395               Harborside           40.7193          -74.0342
3640   2064           Journal Square           40.7337          -74.0625
3677    447             Glenwood Ave           40.7276          -74.0711
3678   1053            Fairmount Ave           40.7257           -74.072
3679    960               Bergen Ave           40.7221          -74.0715
3681   2061                 Grand St           40.7152          -74.0377
3694    255           Jackson Square           40.7111          -74.0789

In [10]:
df.index.name = 'start_station_id'

In [11]:
df.to_csv("startstations.csv")

In [12]:
rowcounter

117066

In [13]:
rowcounter = 0
station = {}
name = {}
lat = {}
lng = {}

for filename in filepaths:
    with open(filename, newline="") as csvfile:
        csvreader = csv.reader(csvfile, delimiter=",")

        next(csvreader)                 # skips header row
        
        # Iterates through each row in csv
        for row in csvreader:
            
            rowcounter += 1

            # if candidate not in dict, adds key and initializes value
            if row[7] not in station:
                station[row[7]] = 0

            station[row[7]] += 1     # increments dictionary value
            
            if row[7] not in name:
                name[row[7]] = row[8]
                
            if row[7] not in lat:
                if row[9] != '0.0':
                    lat[row[7]] = float(row[9])
                
            if row[7] not in lng:
                if row[10] != '0.0':
                    lng[row[7]] = float(row[10])

In [14]:
df_end = pd.DataFrame([station, name, lat, lng]).T
df_end.columns = ['rides', 'end_station_name', 'end_station_lat', 'end_station_lng']

In [15]:
df_end.index.name = 'end_station_id'

In [16]:
# Will export to top level of extracted data archive
df_end.to_csv("endstations.csv")

In [17]:
bikes = {}
tripduration = {}
used = {}

for filename in filepaths:
    with open(filename, newline="") as csvfile:
        csvreader = csv.reader(csvfile, delimiter=",")

        next(csvreader)                 # skips header row
        
        # Iterates through each row in csv
        for row in csvreader:
           
            if row[11] not in bikes:
                bikes[row[11]] = 0

            bikes[row[11]] += 1     # increments dictionary value
            
            if row[11] not in tripduration:
                tripduration[row[11]] = 0.0
            
            tripduration[row[11]] += float(row[0])
            
            if row[11] not in used:
                used[row[11]] = 0.0
            
            used[row[11]] += ((float(row[0]) / 3600) * 11.5)

In [18]:
df_miles = pd.DataFrame([bikes, tripduration, used]).T
df_miles.columns = ['times_used', 'duration', 'miles']

In [19]:
df_miles.index.name = 'bike_id'

In [20]:
# Will export to top level of extracted data archive
df_miles.to_csv("bikes_used.csv")